In [2]:
#Despliegue con HTML sin HTML

In [3]:
# Despliegue

#- Cargamos el modelo
#- Cargamos los datos futuros (Churn_Modelling-future.csv)
#- Preparar los datos futuros
#- Aplicamos el modelo para la predicción

In [4]:
#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

In [5]:
#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

In [6]:
#Cargamos el modelo
import pickle
filename = 'modeloTree-clas-hiper.pkl'
modelTree,labelencoder,variables = pickle.load(open(filename, 'rb'))

In [7]:
#Cargamos los datos futuros (SE COMENTAN LAS DOS LINEAS DESPUES DE ESTE COMENTARIO UNA VEZ CULMINADO TODO EL PROCESO)
#data = pd.read_excel("Churn_Modelling-future.xlsx")
#data.head()

  Geography  Gender  Age    Balance  NumOfProducts IsActiveMember
0    France  Female   42       0.00              1             Si
1     Spain  Female   41   83807.86              1             Si
2    France  Female   42  159660.80              3             No
3    France  Female   39       0.00              2             No
4     Spain  Female   43  125510.82              1             Si

In [ ]:
#Se crea interfaz gráfica con streamlit para capturar los datos
# NOOOOOOO EJECUTARRRR
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de riesgo de Salida de cliente Del Banco')

geography = st.selectbox('Geography', ['France', 'Spain','Germany'])
gender = st.selectbox('Gender', ['Male', 'Female'])
age = st.slider('Age', min_value=18, max_value=96, value=30, step=1)
balance = st.slider('Balance', min_value=0.0, max_value=350000.0, value=10000.0, step=10.0)
numOfProducts = st.slider('NumOfProducts', min_value=1, max_value=4, value=1, step=1)
isActiveMember = st.selectbox('IsActiveMember', ['Si', 'No'])

datos = [[geography, gender, age, balance, numOfProducts, isActiveMember]]
data = pd.DataFrame(datos, columns=['Geography', 'Gender', 'Age', 'Balance', 'NumOfProducts', 'IsActiveMember']) #Dataframe con los mismos nombres de variables

In [8]:
#Se realiza la preparación debe ser igual al aprendizaje
data_preparada=data.copy()
data_preparada = pd.get_dummies(data_preparada, columns=['Geography',  'NumOfProducts'], drop_first=False, dtype=int) #Despliegue siempre drop_first en false
data_preparada = pd.get_dummies(data_preparada, columns=['Gender', 'IsActiveMember'], drop_first=True, dtype=int)
# Alinear columnas con las del modelo entrenado
data_preparada = data_preparada.reindex(columns=variables, fill_value=0)
data_preparada.head()

,Age,Balance,Geography_France,Geography_Germany,Geography_Spain,NumOfProducts_1,NumOfProducts_2,NumOfProducts_3,NumOfProducts_4,Gender_Male,IsActiveMember_Si
0,42,0.00,1,0,0,1,0,0,0,0,1
1,41,83807.86,0,0,1,1,0,0,0,0,1
2,42,159660.80,1,0,0,0,0,1,0,0,0
3,39,0.00,1,0,0,0,1,0,0,0,0
4,43,125510.82,0,0,1,1,0,0,0,0,1

**Predicciones**

In [9]:
#Hacemos la predicción con el Tree
Y_fut = modelTree.predict(data_preparada)
print(Y_fut)

[1 0 1 0 0 0 0 1 0]

In [10]:
# labelencoder
data['Tree']=labelencoder.inverse_transform(Y_fut)
data.head()

  Geography  Gender  Age    Balance  NumOfProducts IsActiveMember Tree
0    France  Female   42       0.00              1             Si   Si
1     Spain  Female   41   83807.86              1             Si   No
2    France  Female   42  159660.80              3             No   Si
3    France  Female   39       0.00              2             No   No
4     Spain  Female   43  125510.82              1             Si   No

In [11]:
data

  Geography  Gender  Age    Balance  NumOfProducts IsActiveMember Tree
0    France  Female   42       0.00              1             Si   Si
1     Spain  Female   41   83807.86              1             Si   No
2    France  Female   42  159660.80              3             No   Si
3    France  Female   39       0.00              2             No   No
4     Spain  Female   43  125510.82              1             Si   No
5     Spain    Male   44  113755.78              2             No   No
6    France    Male   50       0.00              2             Si   No
7   Germany  Female   29  115046.74              4             No   Si
8    France    Male   44  142051.07              2             Si   No